services:
  - type: web
    name: deepseek-telegram-bot
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: DEEPSEEK_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: WHISPER_SIZE
        value: small
      - key: ENABLE_HEALTH
        value: "1"
      - key: CONCURRENCY
        value: "8"
    autoDeploy: true
    healthCheckPath: /health
